In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm
import statsmodels as sms
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
revised_data_us_zips=pd.read_csv("revised_data_us_zips.csv")
revised_loopnet_data_ca = pd.read_csv("revised_loopnet_data_ca.csv")

merged = pd.merge(left = revised_loopnet_data_ca, right = revised_data_us_zips, left_on = "zip" ,
                   right_on ="zip", how = "outer")
merged

id_x    zip                                            address  \
0        1.0  90066  4077 McLaughlin Ave, Los Angeles, CA 90066 - M...   
1       14.0  90066  3451 Beethoven St, Los Angeles, CA 90066 - Mul...   
2       67.0  90066  3814 Lyceum Ave, Los Angeles, CA 90066 - Multi...   
3       74.0  90066  4417 Campbell Dr, Los Angeles, CA 90066 - Mult...   
4      161.0  90066  3611 S Centinela Ave, Los Angeles, CA 90066 - ...   
...      ...    ...                                                ...   
11904    NaN  99923                                                NaN   
11905    NaN  99925                                                NaN   
11906    NaN  99926                                                NaN   
11907    NaN  99927                                                NaN   
11908    NaN  99929                                                NaN   

      price_usd size_sf no_stories property_type year_built year_renovated  \
0       3895000    8156          2   Multifamily       1964             \N   
1       2000000    2700          2   Multifamily       1961             \N   
2       1395000    1624          1   Multifamily       1953             \N   
3       2350000    3646          2   Multifamily       1928           1990   
4       4150000    7266          2   Multifamily       1988             \N   
...         ...     ...        ...           ...        ...            ...   
11904       NaN     NaN        NaN           NaN        NaN            NaN   
11905       NaN     NaN        NaN           NaN        NaN            NaN   
11906       NaN     NaN        NaN           NaN        NaN            NaN   
11907       NaN     NaN        NaN           NaN        NaN            NaN   
11908       NaN     NaN        NaN           NaN        NaN            NaN   

      parking_ratio  ... gross_rent_multiplier   id_y         city state_id  \
0              1.72  ...                 14.35  30059  Los Angeles       CA   
1              1.11  ...                    18  30059  Los Angeles       CA   
2                \N  ...                    \N  30059  Los Angeles       CA   
3               1.1  ...                 13.46  30059  Los Angeles       CA   
4               2.2  ...                  16.2  30059  Los Angeles       CA   
...             ...  ...                   ...    ...          ...      ...   
11904           NaN  ...                   NaN  33117        Hyder       AK   
11905           NaN  ...                   NaN  33118      Klawock       AK   
11906           NaN  ...                   NaN  33119   Metlakatla       AK   
11907           NaN  ...                   NaN  33120  Point Baker       AK   
11908           NaN  ...                   NaN  33121     Wrangell       AK   

       state_name  density            county_name Unnamed: 7 Unnamed: 8  \
0      California     4642            Los Angeles        NaN        NaN   
1      California     4642            Los Angeles        NaN        NaN   
2      California     4642            Los Angeles        NaN        NaN   
3      California     4642            Los Angeles        NaN        NaN   
4      California     4642            Los Angeles        NaN        NaN   
...           ...      ...                    ...        ...        ...   
11904      Alaska      0.3  Prince of Wales-Hyder        NaN        NaN   
11905      Alaska      6.3  Prince of Wales-Hyder        NaN        NaN   
11906      Alaska      4.8  Prince of Wales-Hyder        NaN        NaN   
11907      Alaska        0  Prince of Wales-Hyder        NaN        NaN   
11908      Alaska      0.4               Wrangell        NaN        NaN   

      Unnamed: 9  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
11904        NaN  
11905        NaN  
11906        NaN  
11907        NaN  
11908        NaN  

[11909 rows x 24 columns]

In [3]:
merged=merged.replace(to_replace="\\N",value=np.nan)
merged.replace([np.inf, -np.inf], np.nan, inplace = True)
merged.drop(["Unnamed: 7","Unnamed: 8","Unnamed: 9","year_renovated"],
        axis=1,inplace=True)
merged.dropna(inplace = True)

merged

id_x    zip                                            address  \
0          1.0  90066  4077 McLaughlin Ave, Los Angeles, CA 90066 - M...   
4        161.0  90066  3611 S Centinela Ave, Los Angeles, CA 90066 - ...   
15       927.0  90066  12747 Mitchell Ave, Los Angeles, CA 90066 - Mu...   
54    166435.0  90066  4320 S Centinela Ave, Los Angeles, CA 90066 - ...   
58    168418.0  90066  11411 Washington Pl, Los Angeles, CA 90066 - M...   
...        ...    ...                                                ...   
8625  166269.0  91501  550 E Providencia Ave, Burbank, CA 91501 - Mul...   
8626  166270.0  91501  603 S 6th St, Burbank, CA 91501 - FULLY RENOVA...   
8893  164355.0  90270  5418 Gifford Ave, Maywood, CA 90270 - Multifam...   
8905  175530.0  90240  7348-7350 Florence Avenue, Downey, CA 90240 - ...   
9060  103913.0  90002  8804-8806 Beach St, Los Angeles, CA 90002 - Mu...   

     price_usd size_sf no_stories property_type year_built parking_ratio  \
0      3895000    8156          2   Multifamily       1964          1.72   
4      4150000    7266          2   Multifamily       1988           2.2   
15     2195000    3062          1   Multifamily       1962          1.96   
54     7995000   21268          3   Multifamily       1990          0.71   
58     1600000    3000          2   Multifamily       1952          1.33   
...        ...     ...        ...           ...        ...           ...   
8625   2300000    5768          2   Multifamily       1977          0.87   
8626    999000    2026          1   Multifamily       1948          1.48   
8893    795000    1728          1   Multifamily       1936          3.47   
8905   5500000   15576          2   Multifamily       1960          2.57   
9060   1200000    2848          1   Multifamily       1924          4.21   

     no_units lot_size_ac building_class cap_rate gross_rent_multiplier  \
0          10        0.16              B     4.88                 14.35   
4           9        0.15              B     3.98                  16.2   
15          5        0.16              C        3                 22.88   
54         15        0.24              B     3.45                 16.92   
58          4        0.11              C     3.26                 18.28   
...       ...         ...            ...      ...                   ...   
8625        5        0.16              C     3.53                  18.8   
8626        2        0.16              C     4.52                 16.17   
8893        3        0.14              C     5.75                 13.52   
8905       20        0.94              C     4.08                  14.5   
9060        6         0.2              C     6.16                 12.35   

       id_y         city state_id  state_name density  county_name  
0     30059  Los Angeles       CA  California    4642  Los Angeles  
4     30059  Los Angeles       CA  California    4642  Los Angeles  
15    30059  Los Angeles       CA  California    4642  Los Angeles  
54    30059  Los Angeles       CA  California    4642  Los Angeles  
58    30059  Los Angeles       CA  California    4642  Los Angeles  
...     ...          ...      ...         ...     ...          ...  
8625  30250      Burbank       CA  California  1996.1  Los Angeles  
8626  30250      Burbank       CA  California  1996.1  Los Angeles  
8893  30095      Maywood       CA  California  8350.2  Los Angeles  
8905  30080       Downey       CA  California  3464.1  Los Angeles  
9060  30004  Los Angeles       CA  California  6721.1  Los Angeles  

[692 rows x 20 columns]

In [4]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 692 entries, 0 to 9060
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id_x                   692 non-null    float64
 1   zip                    692 non-null    int64  
 2   address                692 non-null    object 
 3   price_usd              692 non-null    object 
 4   size_sf                692 non-null    object 
 5   no_stories             692 non-null    object 
 6   property_type          692 non-null    object 
 7   year_built             692 non-null    object 
 8   parking_ratio          692 non-null    object 
 9   no_units               692 non-null    object 
 10  lot_size_ac            692 non-null    object 
 11  building_class         692 non-null    object 
 12  cap_rate               692 non-null    object 
 13  gross_rent_multiplier  692 non-null    object 
 14  id_y                   692 non-null    int64  
 15  city 

In [5]:
df=merged.copy()
df.iloc[:,3:6]=df.iloc[:,3:6].astype('float')
df.iloc[:,7:11]=df.iloc[:,7:11].astype('float')
df.iloc[:,12:14]=df.iloc[:,12:14].astype('float')
df.iloc[:,18]=df.iloc[:,18].astype('float')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 692 entries, 0 to 9060
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id_x                   692 non-null    float64
 1   zip                    692 non-null    int64  
 2   address                692 non-null    object 
 3   price_usd              692 non-null    float64
 4   size_sf                692 non-null    float64
 5   no_stories             692 non-null    float64
 6   property_type          692 non-null    object 
 7   year_built             692 non-null    float64
 8   parking_ratio          692 non-null    float64
 9   no_units               692 non-null    float64
 10  lot_size_ac            692 non-null    float64
 11  building_class         692 non-null    object 
 12  cap_rate               692 non-null    float64
 13  gross_rent_multiplier  692 non-null    float64
 14  id_y                   692 non-null    int64  
 15  city 

## Decision Tree

In [7]:
x = df.values[:, [4,5,7,8,9,10,12,13,18]]
y = df.values[:,3]

In [8]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
model = regressor.fit(x, y)

In [9]:
## It can't be predicted using all indpendent variables, thus, we use the size_sf as the most signifcant predictor 

In [10]:
X = df.values[:, 4:5]
Y = df.values[:, 3]
Y.reshape(-1,1)
X.reshape(-1,1)


array([[8156.0],
       [7266.0],
       [3062.0],
       [21268.0],
       [3000.0],
       [7000.0],
       [4986.0],
       [14789.0],
       [14223.0],
       [13201.0],
       [5709.0],
       [13201.0],
       [31845.0],
       [13232.0],
       [10788.0],
       [7358.0],
       [6879.0],
       [15480.0],
       [5312.0],
       [9158.0],
       [4626.0],
       [8812.0],
       [4600.0],
       [4712.0],
       [4212.0],
       [2952.0],
       [6201.0],
       [5000.0],
       [9453.0],
       [5862.0],
       [7566.0],
       [10276.0],
       [9658.0],
       [7712.0],
       [7712.0],
       [9658.0],
       [5060.0],
       [4928.0],
       [4300.0],
       [5624.0],
       [5043.0],
       [12502.0],
       [1959.0],
       [4928.0],
       [4928.0],
       [7972.0],
       [5188.0],
       [6915.0],
       [5260.0],
       [4530.0],
       [19674.0],
       [17674.0],
       [2832.0],
       [18660.0],
       [2980.0],
       [3434.0],
       [5619.0],
       [5552.0],


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=0)

In [14]:
Y_pred = regressor.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[3100000.0 2625000.0]
 [2650000.0 950000.0]
 [2750000.0 3250000.0]
 [1250000.0 949949.0]
 [3600000.0 4700000.0]
 [3895000.0 6000000.0]
 [2000000.0 4495000.0]
 [2275000.0 1200000.0]
 [3295000.0 2345000.0]
 [4900000.0 1280000.0]
 [4150000.0 4895000.0]
 [9650000.0 10300000.0]
 [5064000.0 6950000.0]
 [5450000.0 3325000.0]
 [875000.0 1850000.0]
 [2175000.0 1499000.0]
 [3795000.0 4150000.0]
 [1850000.0 1450000.0]
 [1300000.0 1150000.0]
 [2296000.0 1725000.0]
 [6950000.0 2725000.0]
 [12900000.0 11850000.0]
 [4100000.0 5750000.0]
 [7000000.0 7500000.0]
 [6995000.0 6550000.0]
 [3550000.0 5600000.0]
 [2395000.0 3850000.0]
 [2175000.0 1795000.0]
 [6995000.0 2200000.0]
 [1600000.0 3495000.0]
 [774999.0 595000.0]
 [1200000.0 1475000.0]
 [5295000.0 5445000.0]
 [7250000.0 3295000.0]
 [1750000.0 1900000.0]
 [2695000.0 3200000.0]
 [1560000.0 1700000.0]
 [2850000.0 4800000.0]
 [2700000.0 2800000.0]
 [11880000.0 7500000.0]
 [3200000.0 1720000.0]
 [2750000.0 3250000.0]
 [675000.0 999000.0]
 [1550000.0 24

In [15]:
df3 = Y_pred - Y_test
df3.sort()
df3

array([-10600000.0, -4805000.0, -3600000.0, -3550000.0, -3500000.0,
       -2895000.0, -2895000.0, -2891000.0, -2551000.0, -2495000.0,
       -2105000.0, -2075000.0, -2050000.0, -1955000.0, -1950000.0,
       -1950000.0, -1897000.0, -1895000.0, -1886000.0, -1694500.0,
       -1650000.0, -1597000.0, -1455000.0, -1355000.0, -1350000.0,
       -1350000.0, -1299000.0, -1251000.0, -1105000.0, -1104000.0,
       -1100000.0, -1100000.0, -994000.0, -975000.0, -945000.0, -927500.0,
       -840000.0, -800000.0, -750000.0, -745000.0, -700000.0, -695000.0,
       -655000.0, -650000.0, -625000.0, -585000.0, -545000.0, -515000.0,
       -505000.0, -505000.0, -500000.0, -500000.0, -500000.0, -450000.0,
       -450000.0, -420000.0, -400000.0, -400000.0, -375000.0, -355000.0,
       -355000.0, -325000.0, -324000.0, -305000.0, -300000.0, -300000.0,
       -285000.0, -275000.0, -255000.0, -235000.0, -205000.0, -175000.0,
       -165000.0, -150000.0, -150000.0, -150000.0, -140000.0, -100000.0,
       -100

## Random Forest

In [16]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [17]:
## using the size square feet as the predictor 

In [18]:
from sklearn.ensemble import RandomForestRegressor
regressor1 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor1.fit(X, Y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [19]:
Y_pred1 = regressor1.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[3100000.0 2625000.0]
 [2650000.0 950000.0]
 [2750000.0 3250000.0]
 [1250000.0 949949.0]
 [3600000.0 4700000.0]
 [3895000.0 6000000.0]
 [2000000.0 4495000.0]
 [2275000.0 1200000.0]
 [3295000.0 2345000.0]
 [4900000.0 1280000.0]
 [4150000.0 4895000.0]
 [9650000.0 10300000.0]
 [5064000.0 6950000.0]
 [5450000.0 3325000.0]
 [875000.0 1850000.0]
 [2175000.0 1499000.0]
 [3795000.0 4150000.0]
 [1850000.0 1450000.0]
 [1300000.0 1150000.0]
 [2296000.0 1725000.0]
 [6950000.0 2725000.0]
 [12900000.0 11850000.0]
 [4100000.0 5750000.0]
 [7000000.0 7500000.0]
 [6995000.0 6550000.0]
 [3550000.0 5600000.0]
 [2395000.0 3850000.0]
 [2175000.0 1795000.0]
 [6995000.0 2200000.0]
 [1600000.0 3495000.0]
 [774999.0 595000.0]
 [1200000.0 1475000.0]
 [5295000.0 5445000.0]
 [7250000.0 3295000.0]
 [1750000.0 1900000.0]
 [2695000.0 3200000.0]
 [1560000.0 1700000.0]
 [2850000.0 4800000.0]
 [2700000.0 2800000.0]
 [11880000.0 7500000.0]
 [3200000.0 1720000.0]
 [2750000.0 3250000.0]
 [675000.0 999000.0]
 [1550000.0 24

In [20]:
df4 = Y_pred1 - Y_test
df4.sort()
df4

array([-22867000.1, -18867000.1, -13617000.1, -11367000.1, -11217000.1,
       -10392000.1, -9667000.1, -9367000.1, -8617000.1, -8367000.1,
       -7467000.1, -6867000.1, -6867000.1, -6867000.1, -6617000.1,
       -6417000.1, -6362000.1, -6317000.1, -6317000.1, -6257000.1,
       -6162000.1, -6127000.1, -6067000.1, -5917000.1, -5717000.1,
       -5662000.1, -5617000.1, -5467000.1, -5367000.1, -5117000.1,
       -5017000.1, -4967000.1, -4867000.1, -4812000.1, -4362000.1,
       -4262000.1, -4167000.1, -4067000.1, -3942000.1, -3867000.1,
       -3867000.1, -3862000.1, -3817000.1, -3617000.1, -3517000.1,
       -3442000.1, -3366000.1, -3362000.1, -3317000.1, -3317000.1,
       -3262000.1, -3217000.1, -3167000.1, -3166000.1, -3162000.1,
       -3067000.1, -3062000.1, -2967000.1, -2962000.1, -2942000.1,
       -2917000.1, -2867000.1, -2866000.1, -2862000.1, -2856500.1,
       -2767000.1, -2767000.1, -2762000.1, -2717000.1, -2692000.1,
       -2662000.1, -2662000.1, -2657000.1, -2617000.1, -